# Generated by Django 4.1.1 on 2022-10-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burgersite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
    ]
